---
# Handlers for service configuration role

- name: reload systemd
  systemd:
    daemon_reload: yes
  when: ansible_os_family != 'Windows'

- name: restart tomcat
  systemd:
    name: "{{ tomcat_systemd_service }}"
    state: restarted
  when: ansible_os_family != 'Windows'

- name: stop tomcat
  systemd:
    name: "{{ tomcat_systemd_service }}"
    state: stopped
  when: ansible_os_family != 'Windows'

- name: start tomcat
  systemd:
    name: "{{ tomcat_systemd_service }}"
    state: started
  when: ansible_os_family != 'Windows'

